package com.primege.server;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.HashMap;
import java.util.Map;

import com.google.inject.Inject;

public class DBConnector
{	
	private Connection        _conn     = null ;
	private Statement         _stmt     = null ;
	private PreparedStatement _prepStmt = null ;
	private ResultSet         _rs       = null ;
	
	protected String          _sBase ;
	protected String          _sUser ;
	protected String          _sPass ;

	protected Boolean         _bSimpleMode = false ;
	
	/**
	 * Default constructor
	 * 
	 * @param bMode <code>true</code> for simple mode (where a simple statement is automatically initialized)
	 **/
	public DBConnector(Boolean bMode)
	{
		_bSimpleMode = bMode ;
		
		_sBase  = DbParametersModel.getBase() ;
		_sUser  = DbParametersModel.getUser() ;
		_sPass  = DbParametersModel.getPass() ;
		
		init() ;
		
		if (_bSimpleMode)
			initStatememt() ;
	}
	
	protected void finalize() throws Throwable
	{
		try {
			closeAll() ;
		} 
		finally {
    //  super.finalize() ;
		}
	}
	
	/**
	 * Connect to the database
	 **/
	protected void init()
	{
		try
		{
			Class.forName("com.mysql.jdbc.Driver");
			trace("DBConnector.init: Success loading Mysql Driver", Logger.TraceLevel.DETAIL) ;
		}
		catch(Exception e)
		{
			trace("DBConnector.init: mySql driver not loaded", Logger.TraceLevel.ERROR) ;
			e.printStackTrace();
		}
		
		try
		{
			String sDatabaseName = "jdbc:mysql://localhost:3306/" + _sBase + "?useUnicode=true&characterEncoding=utf-8" ;
			
			_conn = (Connection) DriverManager.getConnection(sDatabaseName, _sUser, _sPass) ;
			trace("DBConnector.init: Connected to database " + sDatabaseName, Logger.TraceLevel.DETAIL) ;
			
		}
		catch(SQLException ex)
		{
			//handle any errors
			trace("DBConnector.init: Error connecting to database " + "jdbc:mysql://localhost:3306/" + _sBase, Logger.TraceLevel.DETAIL) ;
			trace("SQLException:" + ex.getMessage(), Logger.TraceLevel.ERROR);
			trace("SQLState:" + ex.getSQLState(), Logger.TraceLevel.ERROR);
			trace("Error:" +ex.getErrorCode(), Logger.TraceLevel.ERROR);
		}
	}
	
	/**
	 * Initialize a standard statement 
	 **/
	protected void initStatememt()
	{
		if (null == _conn)
		{
			trace("DBConnector.initStatememt: Null connector", Logger.TraceLevel.ERROR) ;
			return ;
		}
		try
		{
			_stmt = (Statement) _conn.createStatement() ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.initStatememt: createStatement failed", Logger.TraceLevel.ERROR) ;
			trace("SQLException:" + ex.getMessage(), Logger.TraceLevel.ERROR);
			trace("SQLState:" + ex.getSQLState(), Logger.TraceLevel.ERROR);
			trace("Error:" +ex.getErrorCode(), Logger.TraceLevel.ERROR);
		}	
	}
	
	public void prepareStatememt(String sPreparedStatementText, int iAutoGeneratedKeys)
	{
		if (null == _conn)
		{
			trace("DBConnector.prepareStatememt: Null connector", Logger.TraceLevel.ERROR) ;
			return ;
		}
		try
		{
			_prepStmt = _conn.prepareStatement(sPreparedStatementText, iAutoGeneratedKeys) ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.prepareStatememt: prepareStatement failed", Logger.TraceLevel.ERROR) ;
			trace("SQLException:" + ex.getMessage(), Logger.TraceLevel.ERROR);
			trace("SQLState:" + ex.getSQLState(), Logger.TraceLevel.ERROR);
			trace("Error:" +ex.getErrorCode(), Logger.TraceLevel.ERROR);
		}	
	}
	
	/**
	 * Create a prepared statement for a query that can return a big result set
	 * 
	 * @param sPreparedStatementText Query text
	 */
	public void prepareStatememtForBigResult(String sPreparedStatementText)
	{
		if (null == _conn)
		{
			trace("DBConnector.prepareStatememt: Null connector", Logger.TraceLevel.ERROR) ;
			return ;
		}
		try
		{
			_prepStmt = _conn.prepareStatement(sPreparedStatementText, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY) ;
			_prepStmt.setFetchSize(Integer.MIN_VALUE) ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.prepareStatememt: prepareStatement failed", Logger.TraceLevel.ERROR) ;
			trace("SQLException:" + ex.getMessage(), Logger.TraceLevel.ERROR);
			trace("SQLState:" + ex.getSQLState(), Logger.TraceLevel.ERROR);
			trace("Error:" +ex.getErrorCode(), Logger.TraceLevel.ERROR);
		}	
	}
	
	public void setStatememtString(int iIndex, String sStatementString)
	{
		if (null == _prepStmt)
		{
			trace("DBConnector.setStatememtString: Null preparedStatement", Logger.TraceLevel.ERROR) ;
			return ;
		}
		try
		{
			_prepStmt.setString(iIndex, sStatementString) ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.setStatememtString: setString failed", Logger.TraceLevel.ERROR) ;
			trace("SQLException:" + ex.getMessage(), Logger.TraceLevel.ERROR);
			trace("SQLState:" + ex.getSQLState(), Logger.TraceLevel.ERROR);
			trace("Error:" +ex.getErrorCode(), Logger.TraceLevel.ERROR);
		}	
	}
	
	public void setStatememtInt(int iIndex, int iStatementInt)
	{
		if (null == _prepStmt)
		{
			trace("DBConnector.setStatememtInt: Null preparedStatement", Logger.TraceLevel.ERROR) ;
			return ;
		}
		try
		{
			_prepStmt.setInt(iIndex, iStatementInt) ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.setStatememtInt: setInt failed", Logger.TraceLevel.ERROR) ;
			trace("SQLException:" + ex.getMessage(), Logger.TraceLevel.ERROR);
			trace("SQLState:" + ex.getSQLState(), Logger.TraceLevel.ERROR);
			trace("Error:" +ex.getErrorCode(), Logger.TraceLevel.ERROR);
		}	
	}
	
	public void setStatememtFloat(int iIndex, float fStatementFloat)
	{
		if (null == _prepStmt)
		{
			trace("setStatememtFloat: Null preparedStatement", Logger.TraceLevel.ERROR) ;
			return ;
		}
		try
		{
			_prepStmt.setFloat(iIndex, fStatementFloat) ;
		}
		catch(SQLException ex)
		{
			trace("setStatememtFloat: setFloat failed", Logger.TraceLevel.ERROR) ;
			trace("SQLException:" + ex.getMessage(), Logger.TraceLevel.ERROR);
			trace("SQLState:" + ex.getSQLState(), Logger.TraceLevel.ERROR);
			trace("Error:" +ex.getErrorCode(), Logger.TraceLevel.ERROR);
		}	
	}
	
	public boolean executePreparedStatement()
	{		
		if (null == _prepStmt)
		{
			trace("DBConnector.executePreparedStatement: Null preparedStatement", Logger.TraceLevel.ERROR) ;
			return false ;
		}
        
		try
		{        
			_rs = _prepStmt.executeQuery() ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.executePreparedStatement: Query failed: " + _prepStmt.toString(), Logger.TraceLevel.ERROR) ;
			trace("SQLException: " + ex.getMessage(), Logger.TraceLevel.ERROR) ;
			trace("SQLState: " + ex.getSQLState(), Logger.TraceLevel.ERROR) ;
			trace("VendorError: " +ex.getErrorCode(), Logger.TraceLevel.ERROR) ;
			return false ;
		}
		
		return true ;
	}
	
	/**
	 * Execute an ordinary query 
	 * 
	 * @param sQuery SQL query
	 * 
	 * @return <code>true</code> if successful
	 **/
	public boolean executeQuery(String sQuery)
	{		
		if (null == _stmt)
		{
			trace("DBConnector.executeQuery: Null statement", Logger.TraceLevel.ERROR) ;
			return false ;
		}
        
		try
		{        
			_rs = _stmt.executeQuery(sQuery) ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.executeQuery: Query failed: " + sQuery, Logger.TraceLevel.ERROR) ;
			trace("SQLException: " + ex.getMessage(), Logger.TraceLevel.ERROR) ;
			trace("SQLState: " + ex.getSQLState(), Logger.TraceLevel.ERROR) ;
			trace("VendorError: " +ex.getErrorCode(), Logger.TraceLevel.ERROR) ;
			return false ;
		}
		
		return true ;
	}
	
	/**
	 * Do "executeUpdate" for a prepared statement 
	 * 
	 * @param bReturnGeneratedKeys : if true, then execute getGeneratedKeys
	 * 
	 * @return Number of affected rows
	 **/
	public int executeUpdatePreparedStatement(boolean bReturnGeneratedKeys)
	{		
		int iNbAffectedRow = -1 ;
		
		if (null == _prepStmt)
		{
			trace("DBConnector.executeUpdatePreparedStatement: Null preparedStatement", Logger.TraceLevel.ERROR) ;
			return iNbAffectedRow ;
		}
        
		try
		{   
			iNbAffectedRow = _prepStmt.executeUpdate() ;
			if ((iNbAffectedRow > 0) && bReturnGeneratedKeys)
				_rs = _prepStmt.getGeneratedKeys() ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.executeUpdatePreparedStatement: Query failed: " + _prepStmt.toString(), Logger.TraceLevel.ERROR) ;
			trace("SQLException: " + ex.getMessage(), Logger.TraceLevel.ERROR) ;
			trace("SQLState: " + ex.getSQLState(), Logger.TraceLevel.ERROR) ;
			trace("VendorError: " +ex.getErrorCode(), Logger.TraceLevel.ERROR) ;
			return -1 ;
		}
		
		return iNbAffectedRow ;
	}
	
	public int executeUpdateQuery(String sQuery, boolean bReturnGeneratedKeys)
	{		
		int iNbAffectedRow = -1 ;
		
		if (null == _stmt)
		{
			trace("DBConnector.executeUpdateQuery: Null statement", Logger.TraceLevel.ERROR) ;
			return iNbAffectedRow ;
		}
        
		try
		{        
			if (bReturnGeneratedKeys)
			{
				iNbAffectedRow = _stmt.executeUpdate(sQuery, Statement.RETURN_GENERATED_KEYS) ;
				_rs = _stmt.getGeneratedKeys() ;
			}
			else
				iNbAffectedRow = _stmt.executeUpdate(sQuery) ;
		}
		catch(SQLException ex)
		{
			trace("DBConnector.executeUpdateQuery: Query failed: " + sQuery, Logger.TraceLevel.ERROR) ;
			trace("SQLException: " + ex.getMessage(), Logger.TraceLevel.ERROR) ;
			trace("SQLState: " + ex.getSQLState(), Logger.TraceLevel.ERROR) ;
			trace("VendorError: " +ex.getErrorCode(), Logger.TraceLevel.ERROR) ;
			return -1 ;
		}
		
		return iNbAffectedRow ;
	}
	
	public Map<String, String> dbSelectPreparedStatement()
	{		
		if (null == _prepStmt)
		{
			trace("DBConnector.dbSelectPreparedStatement: Null preparedStatement", Logger.TraceLevel.ERROR) ;
			return null ;
		}
		
		//ArrayList<Map> selectResult = new ArrayList<Map>();
		Map<String, String> recordInfo = null ;
        
		try
		{        
			_rs = _prepStmt.executeQuery() ;
			if (_rs.next())
			{
        recordInfo = new HashMap<String, String>(); 
                
        ResultSetMetaData rsMetaData = _rs.getMetaData() ;
        int numberOfColumns = rsMetaData.getColumnCount() ;
        for (int i = 1 ; i <= numberOfColumns ; ++i)
        {
        	String sColName = rsMetaData.getColumnName(i) ;
        	recordInfo.put(sColName, _rs.getString(sColName)) ;
        }
        // selectResult.add(recordInfo);*/
				// recordInfo = new HashMap<String, String>() ;
				// recordInfo.put(rs.getString("pseudo"), rs.getString("password")) ;
			}
			
			closeResultSet() ;
			
			// rs.close() ; //close the ResultSet
			// stmt.close() ; //close the statement
		}
		catch(SQLException ex)
		{
			trace("DBConnector.dbSelectPreparedStatement: executeQuery failed for preparedStatement " + _prepStmt.toString(), Logger.TraceLevel.ERROR) ;
			trace("SQLException: " + ex.getMessage(), Logger.TraceLevel.ERROR) ;
			trace("SQLState: " + ex.getSQLState(), Logger.TraceLevel.ERROR) ;
			trace("VendorError: " +ex.getErrorCode(), Logger.TraceLevel.ERROR) ;        
		}
		return recordInfo ;
	}
	
	public Map<String, String> dbSelect(String selectSql)
	{		
		if (null == _stmt)
		{
			trace("DBConnector.dbSelect: Null statement", Logger.TraceLevel.ERROR) ;
			return null ;
		}
		
		//ArrayList<Map> selectResult = new ArrayList<Map>();
		Map<String, String> recordInfo = null ;
        
		try
		{        
			_rs = _stmt.executeQuery(selectSql) ;
			if (_rs.next())
			{
        recordInfo = new HashMap<String, String>(); 
                
        ResultSetMetaData rsMetaData = _rs.getMetaData() ;
        int numberOfColumns = rsMetaData.getColumnCount() ;
        for (int i = 1 ; i <= numberOfColumns ; ++i)
        {
        	String sColName = rsMetaData.getColumnName(i) ;
        	recordInfo.put(sColName, _rs.getString(sColName)) ;
        }
        // selectResult.add(recordInfo);*/
				// recordInfo = new HashMap<String, String>() ;
				// recordInfo.put(rs.getString("pseudo"), rs.getString("password")) ;
			}
			
			closeResultSet() ;
			
			// rs.close() ; //close the ResultSet
			// stmt.close() ; //close the statement
		}
		catch(SQLException ex)
		{
			trace("DBConnector.dbSelect: executeQuery failed for query " + selectSql, Logger.TraceLevel.ERROR) ;
			trace("SQLException: " + ex.getMessage(), Logger.TraceLevel.ERROR) ;
			trace("SQLState: " + ex.getSQLState(), Logger.TraceLevel.ERROR) ;
			trace("VendorError: " +ex.getErrorCode(), Logger.TraceLevel.ERROR) ;        
		}
		return recordInfo ;
	} //end dbSelect(...)
	
	public void closeAll()
	{
		closeResultSet() ;
		
		if (null != _stmt)
		{
			try {
				_stmt.close() ;
				trace("DBConnector.init: Statement closed", Logger.TraceLevel.SUBDETAIL) ;
			}
			catch(SQLException sqlEx) {
				trace("StackTrace:" + sqlEx.getStackTrace(), Logger.TraceLevel.ERROR) ;
			}
		}
		
		closePreparedStatement() ;
		
		if (null != _conn)
		{
			try {
				_conn.close() ;
				trace("DBConnector.init: Connector closed", Logger.TraceLevel.SUBDETAIL) ;
			}
			catch(SQLException sqlEx) {
				trace("StackTrace:" + sqlEx.getStackTrace(), Logger.TraceLevel.ERROR) ;
			}
		}
	}
	
	public void closePreparedStatement()
	{
		if (null == _prepStmt)
			return ;
		
		try
		{
			if (_prepStmt.isClosed())
				return ;
		} catch (SQLException sqlEx)
		{
			trace("StackTrace:" + sqlEx.getStackTrace(), Logger.TraceLevel.ERROR) ;
		}
		
		try {
			_prepStmt.close() ;
			// trace("DBConnector.init: Prepared statement closed", Logger.TraceLevel.SUBDETAIL) ;
		}
		catch(SQLException sqlEx) {
			trace("StackTrace:" + sqlEx.getStackTrace(), Logger.TraceLevel.ERROR) ;
		}
	}
	
	public void closeResultSet()
	{
		if (null == _rs)
			return ;
		
		try
		{
			_rs.close() ;
		}
		catch(SQLException sqlEx)
		{
			trace("StackTrace when closing ResultSet: " + sqlEx.getStackTrace(), Logger.TraceLevel.ERROR) ;
		}
	}
	
	public Statement getStatement() {
		return _stmt ;
	}
	
	public PreparedStatement getPreparedStatement() {
		return _prepStmt ; 
	}
	
	public String getPreparedStatementAsString() {
		return _prepStmt.toString() ; 
	}
	
	public ResultSet getResultSet() {
		return _rs ; 
	}
	
	public Connection getConnection() {
		return _conn ; 
	}
	
	@Inject
	public void trace(String sTraceText, Logger.TraceLevel traceLevel) {
		Logger.trace(sTraceText, -1, traceLevel) ;
	}
}
